site_name: Dorian Baret
theme:
  name: material
  icon:
    logo: fontawesome/solid/square-pen 
  custom_dir: overrides
  features:
    - content.code.copy
    - navigation.tabs
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference
nav:
  - Home:
    - 'index.md'
  - API Naolib:
    - 'list_all_stops.md'
    - 'stops_near_lat_long.md'
    - 'waiting_time_stop.md'
    - "Lalala": 'test.html'
markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
extra_css:
  - stylesheets/extra.css
  - stylesheets/hljs.css
  - https://unpkg.com/leaflet/dist/leaflet.css
  - https://api.mapbox.com/mapbox.js/plugins/leaflet-fullscreen/v1.0.1/leaflet.fullscreen.css
extra_javascript:
  - https://unpkg.com/leaflet/dist/leaflet.js
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.4.0/highlight.min.js
  - https://api.mapbox.com/mapbox.js/plugins/leaflet-fullscreen/v1.0.1/Leaflet.fullscreen.min.js
plugins:
  - search
  - open-in-new-tab